# cd ../../../actioncam
# docker build -t actioncam-app --file ./shell/setup/Dockerfile_actioncam .
# docker run -p 8080:8080 --rm --name actioncam-app-running actioncam-app
FROM python:3

ARG ACTIONCAM_DIR=/home/camuser/actioncam
ARG USERNAME=camuser

ENV ACTIONCAM_DIR=${ACTIONCAM_DIR}
ENV USERNAME=${USERNAME}

COPY ./shell/setup/0_setup_os.sh .
RUN bash -c ./0_setup_os.sh
RUN apt update && apt install -y vim

RUN useradd -ms /bin/bash $USERNAME

RUN mkdir $ACTIONCAM_DIR
RUN mkdir $ACTIONCAM_DIR/data
RUN mkdir $ACTIONCAM_DIR/compressed
RUN mkdir $ACTIONCAM_DIR/log
RUN mkdir $ACTIONCAM_DIR/recordings
RUN mkdir $ACTIONCAM_DIR/send

COPY ./code $ACTIONCAM_DIR/code
COPY ./shell/setup/2_setup_folders.sh $ACTIONCAM_DIR
COPY ./shell/startup/start_actioncam.sh $ACTIONCAM_DIR
COPY ./shell/setup/config.json $ACTIONCAM_DIR
COPY ./shell/setup/requirements.txt $ACTIONCAM_DIR

RUN chmod -R 765 $ACTIONCAM_DIR
RUN chown -R $USERNAME $ACTIONCAM_DIR
RUN chgrp -R $USERNAME $ACTIONCAM_DIR
USER $USERNAME
RUN bash -c $ACTIONCAM_DIR/2_setup_folders.sh 

EXPOSE 8080
WORKDIR $ACTIONCAM_DIR
CMD ${ACTIONCAM_DIR}/start_actioncam.sh