# cd ../../../actioncam
# docker build -t actioncam-app --file ./shell/setup/Dockerfile_actioncam .
# docker run -it --rm --name actioncam-app-running actioncam-app
FROM python:3


# WORKDIR /usr/src/actioncam
COPY ./shell/setup/0_setup_os.sh .
RUN bash -c ./0_setup_os.sh

RUN useradd -ms /bin/bash camuser
USER camuser
COPY ./code /home/camuser
COPY ./shell/setup/2_setup_folders.sh /home/camuser
COPY ./shell/setup/config.json /home/camuser
COPY ./shell/setup/requirements.txt /home/camuser

WORKDIR /home/camuser
RUN ./2_setup_folders.sh 

# source /home/camuser/actioncam/venv/bin/activate
# CMD [ "python", "/home/camuser/actiomcam.py" ]