# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false

  config.ssh.forward_agent = true
  config.ssh.insert_key    = false

  config.vm.hostname = "vactioncam"
  config.vm.network "public_network", ip: "192.168.178.33"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "vactioncam"
      vb.memory = "4096"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/vagrants"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./actioncam-prepare.yml"
  end

end
